# TASK 1
dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Calculate the total global sales for all games in the dataset.


In [2]:
import pandas as pd

df = pd.read_csv("./vgsalesGlobale.csv")

print(f"Total global sales for all games: {df['Global_Sales'].sum()}")

Total global sales for all games: 8920.44


Find the game with the highest global sales.


In [3]:
print(f"Game with highest global sales: {df['Name'][df['Global_Sales'].idxmax()]}")

Game with highest global sales: Wii Sports


Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).


In [4]:
print(f"Average sales for NA_Sales: {df['NA_Sales'].mean()}")
print(f"Average sales for EU_Sales: {df['EU_Sales'].mean()}")
print(f"Average sales for JP_Sales: {df['JP_Sales'].mean()}")
print(f"Average sales for Other_Sales: {df['Other_Sales'].mean()}")

Average sales for NA_Sales: 0.26466742981082064
Average sales for EU_Sales: 0.14665200626581515
Average sales for JP_Sales: 0.077781660441017
Average sales for Other_Sales: 0.0480630196409206


Find the top 5 most popular game genres based on global sales.


In [5]:
print(f"Top 5 most popular genres based on global sales:\
      \n{df.groupby('Genre')['Global_Sales'].sum().sort_values(ascending=False).head(5)}")

Top 5 most popular genres based on global sales:      
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).


In [6]:
total_genre_sales_NA = df.groupby('Genre')['NA_Sales'].sum()
total_genre_sales_EU = df.groupby('Genre')['EU_Sales'].sum()
total_genre_sales_JP = df.groupby('Genre')['JP_Sales'].sum()
total_genre_sales_Other = df.groupby('Genre')['Other_Sales'].sum()

print(f"\nTotal Sales for Each Genre in NA \n{total_genre_sales_NA}")
print(f"\nTotal Sales for Each Genre in JP: \n{total_genre_sales_JP}")
print(f"\nTotal Sales for Each Genre in EU: \n{total_genre_sales_EU}")
print(f"\nTotal Sales for Each Genre in Other: \n{total_genre_sales_Other}")
print(f"\nMost Popular genre in North America: {total_genre_sales_NA.idxmax()}")


Total Sales for Each Genre in NA 
Genre
Action          877.83
Adventure       105.80
Fighting        223.59
Misc            410.24
Platform        447.05
Puzzle          123.78
Racing          359.42
Role-Playing    327.28
Shooter         582.60
Simulation      183.31
Sports          683.35
Strategy         68.70
Name: NA_Sales, dtype: float64

Total Sales for Each Genre in JP: 
Genre
Action          159.95
Adventure        52.07
Fighting         87.35
Misc            107.76
Platform        130.77
Puzzle           57.31
Racing           56.69
Role-Playing    352.31
Shooter          38.28
Simulation       63.70
Sports          135.37
Strategy         49.46
Name: JP_Sales, dtype: float64

Total Sales for Each Genre in EU: 
Genre
Action          525.00
Adventure        64.13
Fighting        101.32
Misc            215.98
Platform        201.63
Puzzle           50.78
Racing          238.39
Role-Playing    188.06
Shooter         313.27
Simulation      113.38
Sports          376.85
Strategy

Display last 10 rows.


In [7]:
df.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

Determine the top 3 gaming platforms with the highest global sales.


In [8]:
print(f"Top 3 most popular gaming platform based on global sales:\
      \n{df.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False).head(3)}")

Top 3 most popular gaming platform based on global sales:      
Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


Calculate the market share (percentage of global sales) for each genre.


In [9]:
genre_globalsales = df.groupby("Genre")['Global_Sales'].sum()
genre_marketshare = genre_globalsales / df['Global_Sales'].sum() * 100
print(genre_marketshare)

Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)


In [ ]:
print(f"Correlation coefficient between NA Sales and EU Sales: {df['NA_Sales'].corr(df['EU_Sales'])}")

Correlation coefficient between NA Sales and EU Sales: 0.767726748370264


## Task 2 English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [13]:
dictionary = {
    "hello": "hola",
    "goodbye": "adiós",
    "please": "por favor",
    "thank you": "gracias",
    "yes": "sí",
    "no": "no",
    "morning": "mañana",
    "night": "noche",
    "food": "comida",
    "water": "agua"
}

while(True):
    user_input = input("Enter an English word (or press enter to exit): ") or "EXIT"
    if user_input == "EXIT":
        break
    
    if user_input in dictionary:
        print(f"Spanish translation: {dictionary[user_input]}")
    else:
        print("Translation not available")

Spanish translation: hola



## Task 3 Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [15]:
def classify_emails(emails: list):
    important_emails = []
    promotional_emails = []
    spam_emails = []
    
    for email in emails:
        if ['Important', 'Urgent'] in email.tolower():
            important_emails.append(email)
        elif [r'% off', 'offer', 'discount', 'deal', 'promotion'] in email.tolower():
            promotional_emails.append(email)
        elif ['lottery', 'prize'] in email.tolower():
            spam_emails.append(email)
    
    print(f"Important emails: {important_emails}")
    print(f"Promotional Emails: {promotional_emails}")
    print(f"Spam Emails: {spam_emails}")
    
    return important_emails, promotional_emails, spam_emails


## Task 4 Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.

In [18]:
shopping_cart = []

print("Welcome to the Online Store!")
print("Available products:")
print("1. AI Response Simulator")
print("2. Investment Decision")
print("3. Exit")

while True:
    choice = input("Enter the ID of the product you want to add to the cart (or 'q' to quit): ") or 'q'

    if choice.lower() == 'q':
        break


    choice = int(choice)
    if choice < 1 or choice > 3:
        print("Invalid choice. Please enter a number between 1 and 3.")
        continue

    if choice == 1:
        shopping_cart.append("AI Response Simulator")
        print("AI Response Simulator has been added to your cart.")
    
    elif choice == 2:
        shopping_cart.append("Investment Decision")
        print("Investment Decision has been added to your cart.")
    
    elif choice == 3:
        break

print("\nYour shopping cart contains:")
print(shopping_cart)

print("Thank you for shopping!")

Welcome to the Online Store!
Available products:
1. AI Response Simulator
2. Investment Decision
3. Exit
AI Response Simulator has been added to your cart.
Investment Decision has been added to your cart.
AI Response Simulator has been added to your cart.
AI Response Simulator has been added to your cart.

Your shopping cart contains:
['AI Response Simulator', 'Investment Decision', 'AI Response Simulator', 'AI Response Simulator']
Thank you for shopping with us! Goodbye!


## Task 5
* Create two NumPy arrays of the same shape and perform element-wise addition on them.
* Calculate the element-wise product of two NumPy arrays.

In [20]:
import numpy as np


arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print(arr1 + arr2)
print(arr1 * arr2)

[ 6  8 10 12]
[ 5 12 21 32]


## Task 6


Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).


In [22]:
arr1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr2D = arr1D.reshape(3, 4)
print(arr2D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Concatenate two NumPy arrays horizontally and vertically.

In [43]:

horizontal_conc = np.concatenate((arr1, arr2))
vertical_conc = np.concatenate((arr1.reshape(1,4), arr2.reshape(1, 4)))

print(f"Horizontal Concatenation: {horizontal_conc}")
print(f"Vertical Concatenation: \n{vertical_conc}")

Horizontal Concatenation: [1 2 3 4 5 6 7 8]
Vertical Concatenation: 
[[1 2 3 4]
 [5 6 7 8]]


## Task 7
* Reverse A List In Python Using Slicing


In [20]:
l = [1, 2, 3, 4, 5]
print(l[::-1])

[5, 4, 3, 2, 1]


# TASK 8
You need to download the GitHub Desktop software, push your lab task to your GitHub account, and share the link on GCR as a submission.